/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/gemeenten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lijst van gemeenten
         * @description Retourneert een gepagineerde lijst van alle gemeenten met hun voortgang en aantal pakketten.
         */
        get: operations["getGemeenten"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gemeenten/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gemeente detail
         * @description Retourneert gedetailleerde informatie over een specifieke gemeente, inclusief samenwerkingen.
         */
        get: operations["getGemeenteById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gemeenten/{id}/pakketten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pakketportfolio van een gemeente
         * @description Retourneert alle softwarepakketten die een gemeente in gebruik heeft, inclusief versie-informatie en referentiecomponenten.
         */
        get: operations["getGemeentePakketten"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leveranciers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lijst van leveranciers
         * @description Retourneert een gepagineerde lijst van alle softwareleveranciers.
         */
        get: operations["getLeveranciers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leveranciers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Leverancier detail
         * @description Retourneert gedetailleerde informatie over een specifieke leverancier, inclusief pakketten.
         */
        get: operations["getLeverancierById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leveranciers/{id}/pakketten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pakketten van een leverancier
         * @description Retourneert alle softwarepakketten van een specifieke leverancier.
         */
        get: operations["getLeverancierPakketten"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiecomponenten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lijst van referentiecomponenten
         * @description Retourneert alle GEMMA referentiecomponenten met het aantal gekoppelde pakketten.
         */
        get: operations["getReferentiecomponenten"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standaarden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lijst van standaarden
         * @description Retourneert alle standaarden met hun versies en het aantal gekoppelde pakketten per versie.
         */
        get: operations["getStandaarden"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/begrippen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lijst van begrippen
         * @description Retourneert alle NL-SBB begrippen uit het NORA begrippenkader, optioneel gefilterd op zoekterm.
         */
        get: operations["getBegrippen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Foutmelding */
            error: string;
        };
        PaginationMeta: {
            /** @description Totaal aantal items */
            total: number;
            /** @description Huidige offset */
            offset: number;
            /** @description Huidige limiet per pagina */
            limit: number;
        };
        GemeenteSummary: {
            /** @description Unieke ID */
            id: string;
            /**
             * @description Naam van de gemeente
             * @example Amsterdam
             */
            naam: string;
            /**
             * @description CBS gemeentecode
             * @example 0363
             */
            cbsCode: string;
            /**
             * @description Voortgangspercentage (0-100)
             * @example 85
             */
            progress: number;
            /**
             * @description Aantal softwarepakketten in gebruik
             * @example 42
             */
            aantalPakketten: number;
        };
        GemeenteDetail: {
            id: string;
            /** @example Amsterdam */
            naam: string;
            /** @example 0363 */
            cbsCode: string;
            /** @example 85 */
            progress: number;
            contactpersoon?: string | null;
            email?: string | null;
            website?: string | null;
            telefoon?: string | null;
            samenwerkingen: {
                /** @example Dimpact */
                naam?: string;
                /** @example Coöperatie */
                type?: string;
            }[];
        };
        GemeentePakket: {
            pakketId?: string;
            /** @example Zaaksysteem */
            pakketNaam?: string;
            /** @example zaaksysteem */
            pakketSlug?: string;
            /** @example 3.2 */
            versie?: string;
            /** @example productie */
            status?: string;
            leverancier?: {
                /** @example Centric */
                naam?: string;
            };
            referentiecomponenten?: {
                naam?: string;
                guid?: string;
            }[];
        };
        LeverancierSummary: {
            id: string;
            /** @example Centric */
            naam: string;
            /** @example centric */
            slug: string;
            contactpersoon?: string | null;
            email?: string | null;
            website?: string | null;
            /** @example 15 */
            aantalPakketten: number;
            /** @description Lijst van addendum-namen */
            addenda?: string[];
        };
        LeverancierDetail: {
            id: string;
            /** @example Centric */
            naam: string;
            /** @example centric */
            slug: string;
            contactpersoon?: string | null;
            email?: string | null;
            website?: string | null;
            telefoon?: string | null;
            addenda?: string[];
            pakketten: {
                id?: string;
                naam?: string;
                slug?: string;
                laatsteVersie?: {
                    naam?: string;
                    status?: string;
                } | null;
            }[];
        };
        LeverancierPakket: {
            id: string;
            /** @example Suite4 */
            naam: string;
            /** @example suite4 */
            slug: string;
            /** @example Centric */
            leverancier?: string;
            laatsteVersie?: {
                /** @example 5.0 */
                naam?: string;
                /** @example In gebruik */
                status?: string;
            } | null;
        };
        Referentiecomponent: {
            id: string;
            /** @example Zaakregistratie */
            naam: string;
            /** @example abc-123 */
            guid: string;
            beschrijving?: string | null;
            /**
             * @description Aantal pakketten dat dit component ondersteunt
             * @example 8
             */
            aantalPakketten: number;
        };
        Begrip: {
            id: string;
            /**
             * @description skos:prefLabel
             * @example Applicatiefunctie
             */
            term: string;
            /**
             * @description skos:definition
             * @example Een functie van een applicatie
             */
            definitie: string;
            /** @description rdfs:comment */
            toelichting?: string | null;
            /** @description skos:scopeNote */
            scopeNote?: string | null;
            /** @description Bronverwijzing */
            bron?: string | null;
            /**
             * @description NL-SBB concept URI
             * @example https://begrippen.noraonline.nl/basisbegrippen/applicatiefunctie
             */
            uri: string;
            /**
             * @description skos:altLabel
             * @example [
             *       "appfunctie"
             *     ]
             */
            synoniemen: string[];
            /**
             * @description SKOSMOS vocabulary ID
             * @example basisbegrippen
             */
            vocab: string;
        };
        Standaard: {
            id: string;
            /** @example StUF */
            naam: string;
            guid: string;
            beschrijving?: string | null;
            versies: {
                id?: string;
                /** @example 3.01 */
                naam?: string;
                /** @example 12 */
                aantalPakketten?: number;
            }[];
            /**
             * @description Som van pakketten over alle versies
             * @example 20
             */
            totaalPakketten: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGemeenten: {
        parameters: {
            query?: {
                /**
                 * @description Zoekterm om gemeenten te filteren op naam
                 * @example Amsterdam
                 */
                zoek?: string;
                /** @description Aantal items om over te slaan (voor paginatie) */
                offset?: number;
                /** @description Maximum aantal items per pagina (max 200) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Succesvolle response met lijst van gemeenten */
            200: {
                headers: {
                    /** @description Totaal aantal gemeenten (ongeacht paginatie) */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["GemeenteSummary"][];
                        meta?: components["schemas"]["PaginationMeta"];
                    };
                };
            };
            /** @description Interne serverfout */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getGemeenteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unieke ID van de gemeente */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Succesvolle response met gemeente details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["GemeenteDetail"];
                    };
                };
            };
            /** @description Gemeente niet gevonden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Interne serverfout */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getGemeentePakketten: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unieke ID van de gemeente */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Succesvolle response met pakketportfolio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["GemeentePakket"][];
                        meta?: {
                            total?: number;
                            gemeenteNaam?: string;
                        };
                    };
                };
            };
            /** @description Gemeente niet gevonden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Interne serverfout */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLeveranciers: {
        parameters: {
            query?: {
                /**
                 * @description Zoekterm om leveranciers te filteren op naam
                 * @example Centric
                 */
                zoek?: string;
                /** @description Aantal items om over te slaan (voor paginatie) */
                offset?: number;
                /** @description Maximum aantal items per pagina (max 200) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Succesvolle response met lijst van leveranciers */
            200: {
                headers: {
                    /** @description Totaal aantal leveranciers */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LeverancierSummary"][];
                        meta?: components["schemas"]["PaginationMeta"];
                    };
                };
            };
            /** @description Interne serverfout */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLeverancierById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unieke ID van de leverancier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Succesvolle response met leverancier details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LeverancierDetail"];
                    };
                };
            };
            /** @description Leverancier niet gevonden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Interne serverfout */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLeverancierPakketten: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unieke ID van de leverancier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Succesvolle response met pakketten */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LeverancierPakket"][];
                        meta?: {
                            total?: number;
                            leverancierNaam?: string;
                        };
                    };
                };
            };
            /** @description Leverancier niet gevonden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Interne serverfout */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReferentiecomponenten: {
        parameters: {
            query?: {
                /**
                 * @description Zoekterm om referentiecomponenten te filteren op naam
                 * @example Zaakregistratie
                 */
                zoek?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Succesvolle response met lijst van referentiecomponenten */
            200: {
                headers: {
                    /** @description Totaal aantal referentiecomponenten */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Referentiecomponent"][];
                        meta?: {
                            total?: number;
                        };
                    };
                };
            };
            /** @description Interne serverfout */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStandaarden: {
        parameters: {
            query?: {
                /**
                 * @description Zoekterm om standaarden te filteren op naam
                 * @example StUF
                 */
                zoek?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Succesvolle response met lijst van standaarden */
            200: {
                headers: {
                    /** @description Totaal aantal standaarden */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Standaard"][];
                        meta?: {
                            total?: number;
                        };
                    };
                };
            };
            /** @description Interne serverfout */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBegrippen: {
        parameters: {
            query?: {
                /**
                 * @description Zoekterm om begrippen te filteren op term of definitie
                 * @example applicatie
                 */
                zoek?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Succesvolle response met lijst van begrippen */
            200: {
                headers: {
                    /** @description Totaal aantal begrippen */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Begrip"][];
                        meta?: {
                            total?: number;
                        };
                    };
                };
            };
            /** @description Interne serverfout */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
