import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const DATABASE_URL =
  process.env.DATABASE_URL ||
  "postgresql://toineschijvenaars@localhost:5432/softwarecatalogus?schema=public";
const adapter = new PrismaPg({ connectionString: DATABASE_URL });
const prisma = new PrismaClient({ adapter });

// All 342 Dutch municipalities (2025) — sourced from CBS/Kadaster GeoJSON
const GEMEENTEN = [
  { naam: "'s-Gravenhage", cbs: "0518" },
  { naam: "'s-Hertogenbosch", cbs: "0796" },
  { naam: "Aa en Hunze", cbs: "1680" },
  { naam: "Aalsmeer", cbs: "0358" },
  { naam: "Aalten", cbs: "0197" },
  { naam: "Achtkarspelen", cbs: "0059" },
  { naam: "Alblasserdam", cbs: "0482" },
  { naam: "Albrandswaard", cbs: "0613" },
  { naam: "Alkmaar", cbs: "0361" },
  { naam: "Almelo", cbs: "0141" },
  { naam: "Almere", cbs: "0034" },
  { naam: "Alphen aan den Rijn", cbs: "0484" },
  { naam: "Alphen-Chaam", cbs: "1723" },
  { naam: "Altena", cbs: "1959" },
  { naam: "Ameland", cbs: "0060" },
  { naam: "Amersfoort", cbs: "0307" },
  { naam: "Amstelveen", cbs: "0362" },
  { naam: "Amsterdam", cbs: "0363" },
  { naam: "Apeldoorn", cbs: "0200" },
  { naam: "Arnhem", cbs: "0202" },
  { naam: "Assen", cbs: "0106" },
  { naam: "Asten", cbs: "0743" },
  { naam: "Baarle-Nassau", cbs: "0744" },
  { naam: "Baarn", cbs: "0308" },
  { naam: "Barendrecht", cbs: "0489" },
  { naam: "Barneveld", cbs: "0203" },
  { naam: "Beek", cbs: "0888" },
  { naam: "Beekdaelen", cbs: "1954" },
  { naam: "Beesel", cbs: "0889" },
  { naam: "Berg en Dal", cbs: "1945" },
  { naam: "Bergeijk", cbs: "1724" },
  { naam: "Bergen (L.)", cbs: "0893" },
  { naam: "Bergen (NH.)", cbs: "0373" },
  { naam: "Bergen op Zoom", cbs: "0748" },
  { naam: "Berkelland", cbs: "1859" },
  { naam: "Bernheze", cbs: "1721" },
  { naam: "Best", cbs: "0753" },
  { naam: "Beuningen", cbs: "0209" },
  { naam: "Beverwijk", cbs: "0375" },
  { naam: "Bladel", cbs: "1728" },
  { naam: "Blaricum", cbs: "0376" },
  { naam: "Bloemendaal", cbs: "0377" },
  { naam: "Bodegraven-Reeuwijk", cbs: "1901" },
  { naam: "Boekel", cbs: "0755" },
  { naam: "Borger-Odoorn", cbs: "1681" },
  { naam: "Borne", cbs: "0147" },
  { naam: "Borsele", cbs: "0654" },
  { naam: "Boxtel", cbs: "0757" },
  { naam: "Breda", cbs: "0758" },
  { naam: "Bronckhorst", cbs: "1876" },
  { naam: "Brummen", cbs: "0213" },
  { naam: "Brunssum", cbs: "0899" },
  { naam: "Bunnik", cbs: "0312" },
  { naam: "Bunschoten", cbs: "0313" },
  { naam: "Buren", cbs: "0214" },
  { naam: "Capelle aan den IJssel", cbs: "0502" },
  { naam: "Castricum", cbs: "0383" },
  { naam: "Coevorden", cbs: "0109" },
  { naam: "Cranendonck", cbs: "1706" },
  { naam: "Culemborg", cbs: "0216" },
  { naam: "Dalfsen", cbs: "0148" },
  { naam: "Dantumadiel", cbs: "1891" },
  { naam: "De Bilt", cbs: "0310" },
  { naam: "De Fryske Marren", cbs: "1940" },
  { naam: "De Ronde Venen", cbs: "0736" },
  { naam: "De Wolden", cbs: "1690" },
  { naam: "Delft", cbs: "0503" },
  { naam: "Den Helder", cbs: "0400" },
  { naam: "Deurne", cbs: "0762" },
  { naam: "Deventer", cbs: "0150" },
  { naam: "Diemen", cbs: "0384" },
  { naam: "Dijk en Waard", cbs: "1980" },
  { naam: "Dinkelland", cbs: "1774" },
  { naam: "Doesburg", cbs: "0221" },
  { naam: "Doetinchem", cbs: "0222" },
  { naam: "Dongen", cbs: "0766" },
  { naam: "Dordrecht", cbs: "0505" },
  { naam: "Drechterland", cbs: "0498" },
  { naam: "Drimmelen", cbs: "1719" },
  { naam: "Dronten", cbs: "0303" },
  { naam: "Druten", cbs: "0225" },
  { naam: "Duiven", cbs: "0226" },
  { naam: "Echt-Susteren", cbs: "1711" },
  { naam: "Edam-Volendam", cbs: "0385" },
  { naam: "Ede", cbs: "0228" },
  { naam: "Eemnes", cbs: "0317" },
  { naam: "Eemsdelta", cbs: "1979" },
  { naam: "Eersel", cbs: "0770" },
  { naam: "Eijsden-Margraten", cbs: "1903" },
  { naam: "Eindhoven", cbs: "0772" },
  { naam: "Elburg", cbs: "0230" },
  { naam: "Emmen", cbs: "0114" },
  { naam: "Enkhuizen", cbs: "0388" },
  { naam: "Enschede", cbs: "0153" },
  { naam: "Epe", cbs: "0232" },
  { naam: "Ermelo", cbs: "0233" },
  { naam: "Etten-Leur", cbs: "0777" },
  { naam: "Geertruidenberg", cbs: "0779" },
  { naam: "Geldrop-Mierlo", cbs: "1771" },
  { naam: "Gemert-Bakel", cbs: "1652" },
  { naam: "Gennep", cbs: "0907" },
  { naam: "Gilze en Rijen", cbs: "0784" },
  { naam: "Goeree-Overflakkee", cbs: "1924" },
  { naam: "Goes", cbs: "0664" },
  { naam: "Goirle", cbs: "0785" },
  { naam: "Gooise Meren", cbs: "1942" },
  { naam: "Gorinchem", cbs: "0512" },
  { naam: "Gouda", cbs: "0513" },
  { naam: "Groningen", cbs: "0014" },
  { naam: "Gulpen-Wittem", cbs: "1729" },
  { naam: "Haaksbergen", cbs: "0158" },
  { naam: "Haarlem", cbs: "0392" },
  { naam: "Haarlemmermeer", cbs: "0394" },
  { naam: "Halderberge", cbs: "1655" },
  { naam: "Hardenberg", cbs: "0160" },
  { naam: "Harderwijk", cbs: "0243" },
  { naam: "Hardinxveld-Giessendam", cbs: "0523" },
  { naam: "Harlingen", cbs: "0072" },
  { naam: "Hattem", cbs: "0244" },
  { naam: "Heemskerk", cbs: "0396" },
  { naam: "Heemstede", cbs: "0397" },
  { naam: "Heerde", cbs: "0246" },
  { naam: "Heerenveen", cbs: "0074" },
  { naam: "Heerlen", cbs: "0917" },
  { naam: "Heeze-Leende", cbs: "1658" },
  { naam: "Heiloo", cbs: "0399" },
  { naam: "Hellendoorn", cbs: "0163" },
  { naam: "Helmond", cbs: "0794" },
  { naam: "Hendrik-Ido-Ambacht", cbs: "0531" },
  { naam: "Hengelo", cbs: "0164" },
  { naam: "Het Hogeland", cbs: "1966" },
  { naam: "Heumen", cbs: "0252" },
  { naam: "Heusden", cbs: "0797" },
  { naam: "Hillegom", cbs: "0534" },
  { naam: "Hilvarenbeek", cbs: "0798" },
  { naam: "Hilversum", cbs: "0402" },
  { naam: "Hoeksche Waard", cbs: "1963" },
  { naam: "Hof van Twente", cbs: "1735" },
  { naam: "Hollands Kroon", cbs: "1911" },
  { naam: "Hoogeveen", cbs: "0118" },
  { naam: "Hoorn", cbs: "0405" },
  { naam: "Horst aan de Maas", cbs: "1507" },
  { naam: "Houten", cbs: "0321" },
  { naam: "Huizen", cbs: "0406" },
  { naam: "Hulst", cbs: "0677" },
  { naam: "IJsselstein", cbs: "0353" },
  { naam: "Kaag en Braassem", cbs: "1884" },
  { naam: "Kampen", cbs: "0166" },
  { naam: "Kapelle", cbs: "0678" },
  { naam: "Katwijk", cbs: "0537" },
  { naam: "Kerkrade", cbs: "0928" },
  { naam: "Koggenland", cbs: "1598" },
  { naam: "Krimpen aan den IJssel", cbs: "0542" },
  { naam: "Krimpenerwaard", cbs: "1931" },
  { naam: "Laarbeek", cbs: "1659" },
  { naam: "Land van Cuijk", cbs: "1982" },
  { naam: "Landgraaf", cbs: "0882" },
  { naam: "Landsmeer", cbs: "0415" },
  { naam: "Lansingerland", cbs: "1621" },
  { naam: "Laren", cbs: "0417" },
  { naam: "Leeuwarden", cbs: "0080" },
  { naam: "Leiden", cbs: "0546" },
  { naam: "Leiderdorp", cbs: "0547" },
  { naam: "Leidschendam-Voorburg", cbs: "1916" },
  { naam: "Lelystad", cbs: "0995" },
  { naam: "Leudal", cbs: "1640" },
  { naam: "Leusden", cbs: "0327" },
  { naam: "Lingewaard", cbs: "1705" },
  { naam: "Lisse", cbs: "0553" },
  { naam: "Lochem", cbs: "0262" },
  { naam: "Loon op Zand", cbs: "0809" },
  { naam: "Lopik", cbs: "0331" },
  { naam: "Losser", cbs: "0168" },
  { naam: "Maasdriel", cbs: "0263" },
  { naam: "Maasgouw", cbs: "1641" },
  { naam: "Maashorst", cbs: "1991" },
  { naam: "Maassluis", cbs: "0556" },
  { naam: "Maastricht", cbs: "0935" },
  { naam: "Medemblik", cbs: "0420" },
  { naam: "Meerssen", cbs: "0938" },
  { naam: "Meierijstad", cbs: "1948" },
  { naam: "Meppel", cbs: "0119" },
  { naam: "Middelburg", cbs: "0687" },
  { naam: "Midden-Delfland", cbs: "1842" },
  { naam: "Midden-Drenthe", cbs: "1731" },
  { naam: "Midden-Groningen", cbs: "1952" },
  { naam: "Moerdijk", cbs: "1709" },
  { naam: "Molenlanden", cbs: "1978" },
  { naam: "Montferland", cbs: "1955" },
  { naam: "Montfoort", cbs: "0335" },
  { naam: "Mook en Middelaar", cbs: "0944" },
  { naam: "Neder-Betuwe", cbs: "1740" },
  { naam: "Nederweert", cbs: "0946" },
  { naam: "Nieuwegein", cbs: "0356" },
  { naam: "Nieuwkoop", cbs: "0569" },
  { naam: "Nijkerk", cbs: "0267" },
  { naam: "Nijmegen", cbs: "0268" },
  { naam: "Nissewaard", cbs: "1930" },
  { naam: "Noardeast-Fryslân", cbs: "1970" },
  { naam: "Noord-Beveland", cbs: "1695" },
  { naam: "Noordenveld", cbs: "1699" },
  { naam: "Noordoostpolder", cbs: "0171" },
  { naam: "Noordwijk", cbs: "0575" },
  { naam: "Nuenen, Gerwen en Nederwetten", cbs: "0820" },
  { naam: "Nunspeet", cbs: "0302" },
  { naam: "Oegstgeest", cbs: "0579" },
  { naam: "Oirschot", cbs: "0823" },
  { naam: "Oisterwijk", cbs: "0824" },
  { naam: "Oldambt", cbs: "1895" },
  { naam: "Oldebroek", cbs: "0269" },
  { naam: "Oldenzaal", cbs: "0173" },
  { naam: "Olst-Wijhe", cbs: "1773" },
  { naam: "Ommen", cbs: "0175" },
  { naam: "Oost Gelre", cbs: "1586" },
  { naam: "Oosterhout", cbs: "0826" },
  { naam: "Ooststellingwerf", cbs: "0085" },
  { naam: "Oostzaan", cbs: "0431" },
  { naam: "Opmeer", cbs: "0432" },
  { naam: "Opsterland", cbs: "0086" },
  { naam: "Oss", cbs: "0828" },
  { naam: "Oude IJsselstreek", cbs: "1509" },
  { naam: "Ouder-Amstel", cbs: "0437" },
  { naam: "Oudewater", cbs: "0589" },
  { naam: "Overbetuwe", cbs: "1734" },
  { naam: "Papendrecht", cbs: "0590" },
  { naam: "Peel en Maas", cbs: "1894" },
  { naam: "Pekela", cbs: "0765" },
  { naam: "Pijnacker-Nootdorp", cbs: "1926" },
  { naam: "Purmerend", cbs: "0439" },
  { naam: "Putten", cbs: "0273" },
  { naam: "Raalte", cbs: "0177" },
  { naam: "Reimerswaal", cbs: "0703" },
  { naam: "Renkum", cbs: "0274" },
  { naam: "Renswoude", cbs: "0339" },
  { naam: "Reusel-De Mierden", cbs: "1667" },
  { naam: "Rheden", cbs: "0275" },
  { naam: "Rhenen", cbs: "0340" },
  { naam: "Ridderkerk", cbs: "0597" },
  { naam: "Rijssen-Holten", cbs: "1742" },
  { naam: "Rijswijk", cbs: "0603" },
  { naam: "Roerdalen", cbs: "1669" },
  { naam: "Roermond", cbs: "0957" },
  { naam: "Roosendaal", cbs: "1674" },
  { naam: "Rotterdam", cbs: "0599" },
  { naam: "Rozendaal", cbs: "0277" },
  { naam: "Rucphen", cbs: "0840" },
  { naam: "Schagen", cbs: "0441" },
  { naam: "Scherpenzeel", cbs: "0279" },
  { naam: "Schiedam", cbs: "0606" },
  { naam: "Schiermonnikoog", cbs: "0088" },
  { naam: "Schouwen-Duiveland", cbs: "1676" },
  { naam: "Simpelveld", cbs: "0965" },
  { naam: "Sint-Michielsgestel", cbs: "0845" },
  { naam: "Sittard-Geleen", cbs: "1883" },
  { naam: "Sliedrecht", cbs: "0610" },
  { naam: "Sluis", cbs: "1714" },
  { naam: "Smallingerland", cbs: "0090" },
  { naam: "Soest", cbs: "0342" },
  { naam: "Someren", cbs: "0847" },
  { naam: "Son en Breugel", cbs: "0848" },
  { naam: "Stadskanaal", cbs: "0037" },
  { naam: "Staphorst", cbs: "0180" },
  { naam: "Stede Broec", cbs: "0532" },
  { naam: "Steenbergen", cbs: "0851" },
  { naam: "Steenwijkerland", cbs: "1708" },
  { naam: "Stein", cbs: "0971" },
  { naam: "Stichtse Vecht", cbs: "1904" },
  { naam: "Súdwest-Fryslân", cbs: "1900" },
  { naam: "Terneuzen", cbs: "0715" },
  { naam: "Terschelling", cbs: "0093" },
  { naam: "Texel", cbs: "0448" },
  { naam: "Teylingen", cbs: "1525" },
  { naam: "Tholen", cbs: "0716" },
  { naam: "Tiel", cbs: "0281" },
  { naam: "Tilburg", cbs: "0855" },
  { naam: "Tubbergen", cbs: "0183" },
  { naam: "Twenterand", cbs: "1700" },
  { naam: "Tynaarlo", cbs: "1730" },
  { naam: "Tytsjerksteradiel", cbs: "0737" },
  { naam: "Uitgeest", cbs: "0450" },
  { naam: "Uithoorn", cbs: "0451" },
  { naam: "Urk", cbs: "0184" },
  { naam: "Utrecht", cbs: "0344" },
  { naam: "Utrechtse Heuvelrug", cbs: "1581" },
  { naam: "Vaals", cbs: "0981" },
  { naam: "Valkenburg aan de Geul", cbs: "0994" },
  { naam: "Valkenswaard", cbs: "0858" },
  { naam: "Veendam", cbs: "0047" },
  { naam: "Veenendaal", cbs: "0345" },
  { naam: "Veere", cbs: "0717" },
  { naam: "Veldhoven", cbs: "0861" },
  { naam: "Velsen", cbs: "0453" },
  { naam: "Venlo", cbs: "0983" },
  { naam: "Venray", cbs: "0984" },
  { naam: "Vijfheerenlanden", cbs: "1961" },
  { naam: "Vlaardingen", cbs: "0622" },
  { naam: "Vlieland", cbs: "0096" },
  { naam: "Vlissingen", cbs: "0718" },
  { naam: "Voerendaal", cbs: "0986" },
  { naam: "Voorne aan Zee", cbs: "1992" },
  { naam: "Voorschoten", cbs: "0626" },
  { naam: "Voorst", cbs: "0285" },
  { naam: "Vught", cbs: "0865" },
  { naam: "Waadhoeke", cbs: "1949" },
  { naam: "Waalre", cbs: "0866" },
  { naam: "Waalwijk", cbs: "0867" },
  { naam: "Waddinxveen", cbs: "0627" },
  { naam: "Wageningen", cbs: "0289" },
  { naam: "Wassenaar", cbs: "0629" },
  { naam: "Waterland", cbs: "0852" },
  { naam: "Weert", cbs: "0988" },
  { naam: "West Betuwe", cbs: "1960" },
  { naam: "West Maas en Waal", cbs: "0668" },
  { naam: "Westerkwartier", cbs: "1969" },
  { naam: "Westerveld", cbs: "1701" },
  { naam: "Westervoort", cbs: "0293" },
  { naam: "Westerwolde", cbs: "1950" },
  { naam: "Westland", cbs: "1783" },
  { naam: "Weststellingwerf", cbs: "0098" },
  { naam: "Wierden", cbs: "0189" },
  { naam: "Wijchen", cbs: "0296" },
  { naam: "Wijdemeren", cbs: "1696" },
  { naam: "Wijk bij Duurstede", cbs: "0352" },
  { naam: "Winterswijk", cbs: "0294" },
  { naam: "Woensdrecht", cbs: "0873" },
  { naam: "Woerden", cbs: "0632" },
  { naam: "Wormerland", cbs: "0880" },
  { naam: "Woudenberg", cbs: "0351" },
  { naam: "Zaanstad", cbs: "0479" },
  { naam: "Zaltbommel", cbs: "0297" },
  { naam: "Zandvoort", cbs: "0473" },
  { naam: "Zeewolde", cbs: "0050" },
  { naam: "Zeist", cbs: "0355" },
  { naam: "Zevenaar", cbs: "0299" },
  { naam: "Zoetermeer", cbs: "0637" },
  { naam: "Zoeterwoude", cbs: "0638" },
  { naam: "Zuidplas", cbs: "1892" },
  { naam: "Zundert", cbs: "0879" },
  { naam: "Zutphen", cbs: "0301" },
  { naam: "Zwartewaterland", cbs: "1896" },
  { naam: "Zwijndrecht", cbs: "0642" },
  { naam: "Zwolle", cbs: "0193" },
];

function randomBetween(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

// Seeded random for reproducibility
function seededRandom(seed: number): () => number {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    return ((s >>> 0) / 0xffffffff);
  };
}

async function main() {
  // Check existing gemeenten
  const existing = await prisma.gemeente.findMany({ select: { id: true, cbsCode: true } });
  const existingByCbs = new Map(existing.map((g) => [g.cbsCode, g.id]));
  console.log(`Existing: ${existing.length} gemeenten in database`);
  console.log(`Target:   ${GEMEENTEN.length} gemeenten in seed`);

  // Get all pakketversie IDs for linking new gemeenten
  const pakketten = await prisma.pakket.findMany({
    include: { versies: { take: 1, orderBy: { createdAt: "desc" } } },
  });
  const versieIds = pakketten
    .filter((p) => p.versies.length > 0)
    .map((p) => p.versies[0].id);
  console.log(`Found ${versieIds.length} pakketversies to link`);

  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const g of GEMEENTEN) {
    const rand = seededRandom(parseInt(g.cbs.replace(/\D/g, "")) || 1000);
    const progress = Math.floor(rand() * 101);

    const existingId = existingByCbs.get(g.cbs);

    if (existingId) {
      // Update name if changed
      await prisma.gemeente.update({
        where: { id: existingId },
        data: { naam: g.naam },
      });
      updated++;
      process.stdout.write(".");
    } else {
      // Create new gemeente + link pakketversies
      const gemeente = await prisma.gemeente.create({
        data: {
          naam: g.naam,
          cbsCode: g.cbs,
          progress,
        },
      });

      // Random ~200 pakketversies per gemeente (range 120-280)
      const aantal = randomBetween(120, 280);
      const shuffled = [...versieIds].sort(() => rand() - 0.5);
      const selected = shuffled.slice(0, Math.min(aantal, versieIds.length));

      await prisma.gemeentePakket.createMany({
        data: selected.map((pakketversieId) => ({
          gemeenteId: gemeente.id,
          pakketversieId,
        })),
        skipDuplicates: true,
      });

      created++;
      process.stdout.write("+");
    }
  }

  console.log(`\nDone! ${created} created, ${updated} updated, ${skipped} skipped`);
  const count = await prisma.gemeente.count();
  const linkCount = await prisma.gemeentePakket.count();
  console.log(`Total: ${count} gemeenten with ${linkCount} pakket links`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
